# Default initial positions for fixed_arm_robot's ros2_control fake system

initial_positions:
  fixed_arm_elbow_joint: 0
  fixed_arm_shoulder_lift_joint: 0
  fixed_arm_shoulder_pan_joint: 0
  fixed_arm_wrist_1_joint: 0
  fixed_arm_wrist_2_joint: 0
  fixed_arm_wrist_3_joint: 0